# Generated by Django 4.1 on 2024-10-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recurrence_task_reaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app.family'),
        ),
    ]
