# Generated by Django 4.1 on 2024-11-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='invitate_url',
            new_name='invite_url',
        ),
    ]
