# Generated by Django 4.1 on 2024-12-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_invitate_url_family_invite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.IntegerField(blank=True, choices=[(0, '👍'), (1, '💖'), (2, '👏'), (3, '🙇\u200d♀️')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('task', 'user', 'reaction_type')},
        ),
    ]
