# Generated by Django 4.1 on 2025-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_managers_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
