# Generated by Django 4.1 on 2025-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_unique_together_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='recurrence_type',
            field=models.IntegerField(choices=[(0, '日'), (1, '週'), (2, '月')]),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], null=True),
        ),
    ]
